type: vbench_video_evaluator

# The vbench prompts for video generation.
prompt_path: ./tools/mm_eval/vbench_metrics/VBench_full_info.json

# The path to the dir of generated videos
videos_path: /path/to/the/generated/videos

# The dir to store the eval results
result_dir: ./outputs/demo-sandbox/vbench_eval_results

# Give a name for this eval
eval_name: <eval_name>

# If true, load the required model for VBench from the cache path of evironment parameter VBENCH_CACHE_DIR
load_ckpt_from_local: false

# The dimensions considered in this eval.
# All dimensions include: ['subject_consistency', 'background_consistency', 'temporal_flickering',
# 'motion_smoothness', 'dynamic_degree', 'aesthetic_quality', 'imaging_quality', 'object_class',
# 'multiple_objects', 'human_action', 'color', 'spatial_relationship', 'scene', 'temporal_style',
# 'appearance_style', 'overall_consistency']
# NOTE: Current version of vbench in pypi lacks of a third party code for motion_smoothness.
# NOTE: Besides, when len(dimension_list) > 1, it would occur an error in video loading.
dimension_list:
  - subject_consistency
  - dynamic_degree
